### ISSUE TITLE
add the guidelines about branches

### ISSUE THREAD

**Issue by dannywillems** [hackerhouseparis/hackerhouseparis.github.io#17]
@n1c01a5 I convert the TODO in issue to be able to discuss about this subject.

I think it would be better to mention it is recommended to checkout to the branch corresponding to the modified post (and maybe based on this branch for this post, do a new branch to avoid conflict after PR and merge).
In this way, GitHub recommends to do PR directly in the same branch.

**Comment by n1c01a5** [comment]
@dannywillems thx for the contribution on the wiki https://github.com/hackerhouseparis/hackerhouseparis.github.io/wiki . I am not sure this process to create a new branch on our repo is necessary but it's a good practise. Why not :)
